/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.codeapp.view;

import java.awt.Frame;

import javax.swing.JButton;
import pk.codeapp.controller.CreateorUpdateTeamController;
import pk.codeapp.model.JumpWindow;
import pk.codeapp.model.Team;


/**
 *
 * @author Jose Pablo Brenes
 */
public class CreateorUpdateTeam extends javax.swing.JFrame implements JumpWindow{

    /**
     * Creates new form CreateTeam
     */
    private String functiontoRealize;
    private Frame beforeWindow;
    private Team updateTeam;
    private CreateorUpdateTeamController controller;
    public CreateorUpdateTeam() {
        initComponents();
        controller = new CreateorUpdateTeamController(this);
        this.setLocationRelativeTo(null);
        btnBack.addActionListener(controller);
        btnAdd.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        txtCoach = new javax.swing.JTextField();
        txtAssistant = new javax.swing.JTextField();
        cmbConfederacy = new javax.swing.JComboBox<>();
        lblCoach2 = new javax.swing.JLabel();
        lblCoach1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCoach = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 200, 60));

        txtName.setBackground(new java.awt.Color(0, 0, 0));
        txtName.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 350, 60));

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("jButton1");
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 650, 210, 60));

        txtCoach.setBackground(new java.awt.Color(0, 0, 0));
        txtCoach.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        txtCoach.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCoach, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 350, 60));

        txtAssistant.setBackground(new java.awt.Color(0, 0, 0));
        txtAssistant.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        txtAssistant.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtAssistant, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 350, 60));

        cmbConfederacy.setBackground(new java.awt.Color(0, 0, 0));
        cmbConfederacy.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbConfederacy.setForeground(new java.awt.Color(255, 255, 255));
        cmbConfederacy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CAF ", "AFC", "UEFA ", "CONCACAF ", "CSF ", " " }));
        getContentPane().add(cmbConfederacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 340, 50));

        lblCoach2.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        lblCoach2.setForeground(new java.awt.Color(255, 255, 255));
        lblCoach2.setText("Confederacy");
        getContentPane().add(lblCoach2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, -1, -1));

        lblCoach1.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        lblCoach1.setForeground(new java.awt.Color(255, 255, 255));
        lblCoach1.setText("Assistant");
        getContentPane().add(lblCoach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, -1, -1));

        lblName.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        lblCoach.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        lblCoach.setForeground(new java.awt.Color(255, 255, 255));
        lblCoach.setText("Coach");
        getContentPane().add(lblCoach, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/view/image/secundary5.jpg"))); // NOI18N
        getContentPane().add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateorUpdateTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateorUpdateTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateorUpdateTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateorUpdateTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateorUpdateTeam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    public javax.swing.JComboBox<String> cmbConfederacy;
    private javax.swing.JLabel lblCoach;
    private javax.swing.JLabel lblCoach1;
    private javax.swing.JLabel lblCoach2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    public javax.swing.JTextField txtAssistant;
    public javax.swing.JTextField txtCoach;
    public javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables



    public String getFunctiontoRealize() {
        return functiontoRealize;
    }

    public void setFunctiontoRealize(String functiontoReaalize) {
        this.functiontoRealize = functiontoReaalize;
    }
    
   @Override
    public void openWindow(Frame menuTeams){
        this.beforeWindow=menuTeams;
        this.setVisible(true);
        controller.fillLines();
    }

    @Override
    public void jumpBeforeWindow() {
        this.dispose();
        MenuTeams.controller.addTeamInGridPane(Lobby.controller.getTeams());
        beforeWindow.setVisible(true);
    }

    public Team getUpdateTeam() {
        return updateTeam;
    }

    public void setUpdateTeam(Team updateTeam) {
        this.updateTeam = updateTeam;
    }

    public JButton getBtnAdd() {
        return btnAdd;
    }

    public void setBtnAdd(JButton btnAdd) {
        this.btnAdd = btnAdd;
    }

    public JButton getBtnBack() {
        return btnBack;
    }

    public void setBtnBack(JButton btnBack) {
        this.btnBack = btnBack;
    }
    
}
