/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.codeapp.view;

import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JTextField;
import pk.codeapp.controller.CreateorUpdatePlayerController;
import pk.codeapp.model.JumpWindow;
import pk.codeapp.model.Player;

/**
 *
 * @author Jose Pablo Brenes
 */
public class CreateorUpdatePlayer extends javax.swing.JFrame implements JumpWindow {

    /**
     * Creates new form CreateorUpdatePlayer
     */
    private ShowPlayers beforeWindow;
    CreateorUpdatePlayerController controller;
    private Player actualPlayer;
    public CreateorUpdatePlayer() {
        initComponents();
        this.setLocationRelativeTo(null);
        controller = new CreateorUpdatePlayerController(this);
        btnBack.addActionListener(controller);
        btnAdd.addActionListener(controller);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtGoals = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtNYellowCard1 = new javax.swing.JTextField();
        txtNRedCard = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblGoals = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        lblNRedCard1 = new javax.swing.JLabel();
        lblNRedCard = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        btnBack.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<2018 FIFA WORLD CUP RUSSIA™");
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(785, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 50));

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Default");
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 570, 210, 60));

        txtGoals.setBackground(new java.awt.Color(0, 0, 0));
        txtGoals.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtGoals.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtGoals, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 270, 50));

        txtNumber.setBackground(new java.awt.Color(0, 0, 0));
        txtNumber.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtNumber.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 270, 50));

        txtNYellowCard1.setBackground(new java.awt.Color(0, 0, 0));
        txtNYellowCard1.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtNYellowCard1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtNYellowCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 270, 50));

        txtNRedCard.setBackground(new java.awt.Color(0, 0, 0));
        txtNRedCard.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtNRedCard.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtNRedCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 270, 50));

        txtAge.setBackground(new java.awt.Color(0, 0, 0));
        txtAge.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtAge.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 270, 50));

        txtPosition.setBackground(new java.awt.Color(0, 0, 0));
        txtPosition.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtPosition.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 270, 50));

        txtName.setBackground(new java.awt.Color(0, 0, 0));
        txtName.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 270, 50));

        lblGoals.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        lblGoals.setForeground(new java.awt.Color(255, 255, 255));
        lblGoals.setText("Goals");
        getContentPane().add(lblGoals, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, -1));

        lblNumber.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        lblNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblNumber.setText("Number");
        getContentPane().add(lblNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, -1, -1));

        lblNRedCard1.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        lblNRedCard1.setForeground(new java.awt.Color(255, 255, 255));
        lblNRedCard1.setText("NYellowCard");
        getContentPane().add(lblNRedCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, -1));

        lblNRedCard.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        lblNRedCard.setForeground(new java.awt.Color(255, 255, 255));
        lblNRedCard.setText("NRedCard");
        getContentPane().add(lblNRedCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, -1));

        lblAge.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        lblAge.setForeground(new java.awt.Color(255, 255, 255));
        lblAge.setText("Age");
        getContentPane().add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        lblPosition.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        lblPosition.setForeground(new java.awt.Color(255, 255, 255));
        lblPosition.setText("Position");
        getContentPane().add(lblPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        lblName.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Segundo Semestre 2017\\POO\\Proyecto#2\\RusiaIsComing\\WorldCup2018\\Clases\\WorldCup2018\\WorldChampionCup\\src\\pk\\codeapp\\view\\image\\secundary5.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateorUpdatePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateorUpdatePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateorUpdatePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateorUpdatePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateorUpdatePlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    public javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblGoals;
    private javax.swing.JLabel lblNRedCard;
    private javax.swing.JLabel lblNRedCard1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtGoals;
    private javax.swing.JTextField txtNRedCard;
    private javax.swing.JTextField txtNYellowCard1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtPosition;
    // End of variables declaration//GEN-END:variables

    @Override
    public void openWindow(Frame beforeWindow) {
        this.setVisible(true);
        this.beforeWindow=(ShowPlayers)beforeWindow;
        controller.fillData(actualPlayer);
    }

    @Override
    public void jumpBeforeWindow() {
       this.dispose();
       this.beforeWindow.setVisible(true);
    }

    public JButton getBtnBack() {
        return btnBack;
    }

    public void setBtnBack(JButton btnBack) {
        this.btnBack = btnBack;
    }

    public ShowPlayers getBeforeWindow() {
        return beforeWindow;
    }

    public void setBeforeWindow(ShowPlayers beforeWindow) {
        this.beforeWindow = beforeWindow;
    }

    public JButton getBtnAdd() {
        return btnAdd;
    }

    public void setBtnAdd(JButton btnAdd) {
        this.btnAdd = btnAdd;
    }

    public Player getActualPlayer() {
        return actualPlayer;
    }

    public void setActualPlayer(Player actualPlayer) {
        this.actualPlayer = actualPlayer;
    }

    public JTextField getTxtAge() {
        return txtAge;
    }

    public void setTxtAge(JTextField txtAge) {
        this.txtAge = txtAge;
    }

    public JTextField getTxtGoals() {
        return txtGoals;
    }

    public void setTxtGoals(JTextField txtGoals) {
        this.txtGoals = txtGoals;
    }

    public JTextField getTxtNRedCard() {
        return txtNRedCard;
    }

    public void setTxtNRedCard(JTextField txtNRedCard) {
        this.txtNRedCard = txtNRedCard;
    }

    public JTextField getTxtNYellowCard1() {
        return txtNYellowCard1;
    }

    public void setTxtNYellowCard1(JTextField txtNYellowCard1) {
        this.txtNYellowCard1 = txtNYellowCard1;
    }

    public JTextField getTxtName() {
        return txtName;
    }

    public void setTxtName(JTextField txtName) {
        this.txtName = txtName;
    }

    public JTextField getTxtNumber() {
        return txtNumber;
    }

    public void setTxtNumber(JTextField txtNumber) {
        this.txtNumber = txtNumber;
    }

    public JTextField getTxtPosition() {
        return txtPosition;
    }

    public void setTxtPosition(JTextField txtPosition) {
        this.txtPosition = txtPosition;
    }
    
    
    
}
