/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.codeapp.view;

import java.awt.Frame;
import pk.codeapp.controller.EditGroupController;
import pk.codeapp.model.Group;
import pk.codeapp.model.JumpWindow;

/**
 *
 * @author Daniel Amador
 */
public class EditGroup extends javax.swing.JFrame implements JumpWindow {

    private GroupScreen beforeWindow;
    private EditGroupController editGroup;

    /**
     * Creates new form EditGroup
     */
    public EditGroup() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group1 = new javax.swing.ButtonGroup();
        group2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        paneGroup1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblA1 = new javax.swing.JLabel();
        lblA2 = new javax.swing.JLabel();
        lblA3 = new javax.swing.JLabel();
        lblA4 = new javax.swing.JLabel();
        nameA4 = new javax.swing.JLabel();
        nameA1 = new javax.swing.JLabel();
        nameA2 = new javax.swing.JLabel();
        nameA3 = new javax.swing.JLabel();
        op4 = new javax.swing.JRadioButton();
        op1 = new javax.swing.JRadioButton();
        op2 = new javax.swing.JRadioButton();
        op3 = new javax.swing.JRadioButton();
        paneGroup2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblC1 = new javax.swing.JLabel();
        lblC2 = new javax.swing.JLabel();
        lblC3 = new javax.swing.JLabel();
        lblC4 = new javax.swing.JLabel();
        nameC4 = new javax.swing.JLabel();
        nameC1 = new javax.swing.JLabel();
        nameC2 = new javax.swing.JLabel();
        nameC3 = new javax.swing.JLabel();
        ch2 = new javax.swing.JRadioButton();
        ch3 = new javax.swing.JRadioButton();
        ch4 = new javax.swing.JRadioButton();
        ch1 = new javax.swing.JRadioButton();
        cmbTeams = new javax.swing.JComboBox<>();
        btnMakeChange = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        btnBack.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<2018 FIFA WORLD CUP RUSSIA™");
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(785, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 50));

        paneGroup1.setBackground(new java.awt.Color(250, 250, 240));
        paneGroup1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(51, 153, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Editing");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 40));

        paneGroup1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblA1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneGroup1.add(lblA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 42, 28));

        lblA2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneGroup1.add(lblA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 42, 28));

        lblA3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneGroup1.add(lblA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 42, 28));

        lblA4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneGroup1.add(lblA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 42, 28));

        nameA4.setText("Team Name");
        paneGroup1.add(nameA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 225, -1, -1));

        nameA1.setText("Team Name");
        paneGroup1.add(nameA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 65, -1, -1));

        nameA2.setText("Team Name");
        paneGroup1.add(nameA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 125, -1, -1));

        nameA3.setText("Team Name");
        paneGroup1.add(nameA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 175, -1, -1));

        group1.add(op4);
        paneGroup1.add(op4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 225, -1, -1));

        group1.add(op1);
        paneGroup1.add(op1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 65, -1, -1));

        group1.add(op2);
        paneGroup1.add(op2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 125, -1, -1));

        group1.add(op3);
        paneGroup1.add(op3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 175, -1, -1));

        getContentPane().add(paneGroup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 250, 300));

        paneGroup2.setBackground(new java.awt.Color(250, 250, 240));
        paneGroup2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(51, 153, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Change");
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 40));

        paneGroup2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        lblC1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneGroup2.add(lblC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 42, 28));

        lblC2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneGroup2.add(lblC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 42, 28));

        lblC3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneGroup2.add(lblC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 42, 28));

        lblC4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneGroup2.add(lblC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 42, 28));

        nameC4.setText("Team Name");
        paneGroup2.add(nameC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 225, -1, -1));

        nameC1.setText("Team Name");
        paneGroup2.add(nameC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 65, -1, -1));

        nameC2.setText("Team Name");
        paneGroup2.add(nameC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 125, -1, -1));

        nameC3.setText("Team Name");
        paneGroup2.add(nameC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 175, -1, -1));

        group2.add(ch2);
        paneGroup2.add(ch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 125, -1, -1));

        group2.add(ch3);
        paneGroup2.add(ch3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 175, -1, -1));

        group2.add(ch4);
        paneGroup2.add(ch4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 225, -1, -1));

        group2.add(ch1);
        paneGroup2.add(ch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 65, -1, -1));

        getContentPane().add(paneGroup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 290, 250, 290));

        cmbTeams.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Group" }));
        getContentPane().add(cmbTeams, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, 250, 50));

        btnMakeChange.setBackground(new java.awt.Color(0, 0, 0));
        btnMakeChange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnMakeChange.setText("Make Change");
        getContentPane().add(btnMakeChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/view/image/secundary3.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditGroup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBack;
    public javax.swing.JButton btnMakeChange;
    public javax.swing.JRadioButton ch1;
    public javax.swing.JRadioButton ch2;
    public javax.swing.JRadioButton ch3;
    public javax.swing.JRadioButton ch4;
    public javax.swing.JComboBox<String> cmbTeams;
    public javax.swing.ButtonGroup group1;
    public javax.swing.ButtonGroup group2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JLabel lblA1;
    public javax.swing.JLabel lblA2;
    public javax.swing.JLabel lblA3;
    public javax.swing.JLabel lblA4;
    public javax.swing.JLabel lblC1;
    public javax.swing.JLabel lblC2;
    public javax.swing.JLabel lblC3;
    public javax.swing.JLabel lblC4;
    public javax.swing.JLabel nameA1;
    public javax.swing.JLabel nameA2;
    public javax.swing.JLabel nameA3;
    public javax.swing.JLabel nameA4;
    public javax.swing.JLabel nameC1;
    public javax.swing.JLabel nameC2;
    public javax.swing.JLabel nameC3;
    public javax.swing.JLabel nameC4;
    public javax.swing.JRadioButton op1;
    public javax.swing.JRadioButton op2;
    public javax.swing.JRadioButton op3;
    public javax.swing.JRadioButton op4;
    private javax.swing.JPanel paneGroup1;
    private javax.swing.JPanel paneGroup2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void openWindow(Frame beforeWindow) {
        this.beforeWindow = (GroupScreen) beforeWindow;
        this.setVisible(true);
    }

    @Override
    public void jumpBeforeWindow() {
        this.dispose();
        beforeWindow.setVisible(true);
        
    }

    private void setAction() {
        btnBack.addActionListener(editGroup);
        cmbTeams.addActionListener(editGroup);
        btnMakeChange.addActionListener(editGroup);
    }

    public void initData(Group gr) {
     editGroup = new EditGroupController(gr, this);
     setAction();
    }
}
