/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.codeapp.view;

import java.awt.Frame;
import pk.codeapp.controller.GroupController;
import pk.codeapp.model.JumpWindow;

/**
 *
 * @author Daniel Amador
 */
public class GroupScreen extends javax.swing.JFrame implements JumpWindow{
    private Lobby beforeWindow;
    private GroupController gController;
    /**
     * Creates new form GroupScreen
     */
    public GroupScreen() {
        initComponents();
        gController= new GroupController(this);
        addAtionPerformat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneGroup1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnEditA = new javax.swing.JButton();
        paneGroup2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnEditB = new javax.swing.JButton();
        paneGroup3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnEditC = new javax.swing.JButton();
        paneGroup4 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnEditD = new javax.swing.JButton();
        paneGroup5 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnEditE = new javax.swing.JButton();
        paneGroup6 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnEditG = new javax.swing.JButton();
        paneGroup8 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnEditH = new javax.swing.JButton();
        paneGroup7 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnEditF = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneGroup1.setBackground(new java.awt.Color(250, 250, 240));

        jPanel9.setBackground(new java.awt.Color(51, 153, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Group A");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        btnEditA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/view/image/iconEdit.png"))); // NOI18N
        jPanel9.add(btnEditA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 60, 40));

        javax.swing.GroupLayout paneGroup1Layout = new javax.swing.GroupLayout(paneGroup1);
        paneGroup1.setLayout(paneGroup1Layout);
        paneGroup1Layout.setHorizontalGroup(
            paneGroup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paneGroup1Layout.setVerticalGroup(
            paneGroup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneGroup1Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 260, Short.MAX_VALUE))
        );

        getContentPane().add(paneGroup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 250, 300));

        paneGroup2.setBackground(new java.awt.Color(250, 250, 240));

        jPanel10.setBackground(new java.awt.Color(51, 153, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Group B");
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        btnEditB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/view/image/iconEdit.png"))); // NOI18N
        jPanel10.add(btnEditB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 60, 40));

        javax.swing.GroupLayout paneGroup2Layout = new javax.swing.GroupLayout(paneGroup2);
        paneGroup2.setLayout(paneGroup2Layout);
        paneGroup2Layout.setHorizontalGroup(
            paneGroup2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paneGroup2Layout.setVerticalGroup(
            paneGroup2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneGroup2Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 260, Short.MAX_VALUE))
        );

        getContentPane().add(paneGroup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 250, 300));

        paneGroup3.setBackground(new java.awt.Color(250, 250, 240));

        jPanel11.setBackground(new java.awt.Color(51, 153, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Group C");
        jPanel11.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        btnEditC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/view/image/iconEdit.png"))); // NOI18N
        jPanel11.add(btnEditC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 60, 40));

        javax.swing.GroupLayout paneGroup3Layout = new javax.swing.GroupLayout(paneGroup3);
        paneGroup3.setLayout(paneGroup3Layout);
        paneGroup3Layout.setHorizontalGroup(
            paneGroup3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paneGroup3Layout.setVerticalGroup(
            paneGroup3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneGroup3Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 260, Short.MAX_VALUE))
        );

        getContentPane().add(paneGroup3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 250, 300));

        paneGroup4.setBackground(new java.awt.Color(250, 250, 240));

        jPanel12.setBackground(new java.awt.Color(51, 153, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Group D");
        jPanel12.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        btnEditD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/view/image/iconEdit.png"))); // NOI18N
        jPanel12.add(btnEditD, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 60, 40));

        javax.swing.GroupLayout paneGroup4Layout = new javax.swing.GroupLayout(paneGroup4);
        paneGroup4.setLayout(paneGroup4Layout);
        paneGroup4Layout.setHorizontalGroup(
            paneGroup4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paneGroup4Layout.setVerticalGroup(
            paneGroup4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneGroup4Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 260, Short.MAX_VALUE))
        );

        getContentPane().add(paneGroup4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 90, 250, 300));

        paneGroup5.setBackground(new java.awt.Color(250, 250, 240));

        jPanel13.setBackground(new java.awt.Color(51, 153, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Group E");
        jPanel13.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        btnEditE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/view/image/iconEdit.png"))); // NOI18N
        jPanel13.add(btnEditE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 60, 40));

        javax.swing.GroupLayout paneGroup5Layout = new javax.swing.GroupLayout(paneGroup5);
        paneGroup5.setLayout(paneGroup5Layout);
        paneGroup5Layout.setHorizontalGroup(
            paneGroup5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paneGroup5Layout.setVerticalGroup(
            paneGroup5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneGroup5Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 260, Short.MAX_VALUE))
        );

        getContentPane().add(paneGroup5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 250, 300));

        paneGroup6.setBackground(new java.awt.Color(250, 250, 240));

        jPanel15.setBackground(new java.awt.Color(51, 153, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Group G");
        jPanel15.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        btnEditG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/view/image/iconEdit.png"))); // NOI18N
        jPanel15.add(btnEditG, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 60, 40));

        javax.swing.GroupLayout paneGroup6Layout = new javax.swing.GroupLayout(paneGroup6);
        paneGroup6.setLayout(paneGroup6Layout);
        paneGroup6Layout.setHorizontalGroup(
            paneGroup6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paneGroup6Layout.setVerticalGroup(
            paneGroup6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneGroup6Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 260, Short.MAX_VALUE))
        );

        getContentPane().add(paneGroup6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 250, 300));

        paneGroup8.setBackground(new java.awt.Color(250, 250, 240));

        jPanel16.setBackground(new java.awt.Color(51, 153, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Group H");
        jPanel16.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        btnEditH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/view/image/iconEdit.png"))); // NOI18N
        jPanel16.add(btnEditH, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 60, 40));

        javax.swing.GroupLayout paneGroup8Layout = new javax.swing.GroupLayout(paneGroup8);
        paneGroup8.setLayout(paneGroup8Layout);
        paneGroup8Layout.setHorizontalGroup(
            paneGroup8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneGroup8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        paneGroup8Layout.setVerticalGroup(
            paneGroup8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneGroup8Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 260, Short.MAX_VALUE))
        );

        getContentPane().add(paneGroup8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 400, 250, 300));

        paneGroup7.setBackground(new java.awt.Color(250, 250, 240));

        jPanel14.setBackground(new java.awt.Color(51, 153, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Group F");
        jPanel14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        btnEditF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/view/image/iconEdit.png"))); // NOI18N
        jPanel14.add(btnEditF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 60, 40));

        javax.swing.GroupLayout paneGroup7Layout = new javax.swing.GroupLayout(paneGroup7);
        paneGroup7.setLayout(paneGroup7Layout);
        paneGroup7Layout.setHorizontalGroup(
            paneGroup7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paneGroup7Layout.setVerticalGroup(
            paneGroup7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneGroup7Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 260, Short.MAX_VALUE))
        );

        getContentPane().add(paneGroup7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 250, 300));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        btnBack.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<2018 FIFA WORLD CUP RUSSIA™");
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(785, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 50));

        jLabel1.setBackground(new java.awt.Color(250, 250, 240));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/view/image/ticket.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBack;
    public javax.swing.JButton btnEditA;
    public javax.swing.JButton btnEditB;
    public javax.swing.JButton btnEditC;
    public javax.swing.JButton btnEditD;
    public javax.swing.JButton btnEditE;
    public javax.swing.JButton btnEditF;
    public javax.swing.JButton btnEditG;
    public javax.swing.JButton btnEditH;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel paneGroup1;
    private javax.swing.JPanel paneGroup2;
    private javax.swing.JPanel paneGroup3;
    private javax.swing.JPanel paneGroup4;
    private javax.swing.JPanel paneGroup5;
    private javax.swing.JPanel paneGroup6;
    private javax.swing.JPanel paneGroup7;
    private javax.swing.JPanel paneGroup8;
    // End of variables declaration//GEN-END:variables

    @Override
    public void openWindow(Frame beforeWindow) {
        this.beforeWindow = (Lobby) beforeWindow;
        this.setVisible(true);
    }
    

    @Override
    public void jumpBeforeWindow() {
        this.dispose();
        beforeWindow.setVisible(true);
    }
    public void addAtionPerformat(){
        btnBack.addActionListener(gController);
        btnEditA.addActionListener(gController);
        btnEditB.addActionListener(gController);
        btnEditC.addActionListener(gController);
        btnEditD.addActionListener(gController);
        btnEditE.addActionListener(gController);
        btnEditF.addActionListener(gController);
        btnEditG.addActionListener(gController);
        btnEditH.addActionListener(gController);
        
    }
}
