/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.codeapp.view;

import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import pk.codeapp.controller.PlayerController;
import pk.codeapp.model.JumpWindow;
import pk.codeapp.model.Team;

/**
 *
 * @author Jose Pablo Brenes
 */
public class ShowPlayers extends javax.swing.JFrame implements JumpWindow {

    /**
     * Creates new form showPlayers
     */
    private Team actualTeam;
    private Frame beforeWindow;
    public static PlayerController controller;

    public ShowPlayers(Team actualTeam) {
        initComponents();
        this.actualTeam = actualTeam;
        this.setLocationRelativeTo(null);
        controller = new PlayerController(this);
        btnBack.addActionListener(controller);
        btnCreate.addActionListener(controller);
        btnDelete.addActionListener(controller);
        btnUpdate.addActionListener(controller);
        
    }

    public ShowPlayers() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePlayers = new javax.swing.JTable();
        lblConfederacy = new javax.swing.JLabel();
        lblCon = new javax.swing.JLabel();
        lblAssistant = new javax.swing.JLabel();
        lblN = new javax.swing.JLabel();
        lblAss = new javax.swing.JLabel();
        lblCoach = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        btnBack.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<2018 FIFA WORLD CUP RUSSIA™");
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(785, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 50));

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 650, 180, 60));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 650, 180, 60));

        btnCreate.setBackground(new java.awt.Color(0, 0, 0));
        btnCreate.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create");
        getContentPane().add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 650, 180, 60));

        tablePlayers.setBackground(new java.awt.Color(0, 0, 0));
        tablePlayers.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        tablePlayers.setForeground(new java.awt.Color(255, 255, 255));
        tablePlayers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablePlayers);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 940, 570));

        lblConfederacy.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        lblConfederacy.setForeground(new java.awt.Color(255, 255, 255));
        lblConfederacy.setText("Default");
        getContentPane().add(lblConfederacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        lblCon.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        lblCon.setForeground(new java.awt.Color(255, 255, 255));
        lblCon.setText("Confederacy");
        getContentPane().add(lblCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        lblAssistant.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        lblAssistant.setForeground(new java.awt.Color(255, 255, 255));
        lblAssistant.setText("Default");
        getContentPane().add(lblAssistant, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        lblN.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        lblN.setForeground(new java.awt.Color(255, 255, 255));
        lblN.setText("Name");
        getContentPane().add(lblN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        lblAss.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        lblAss.setForeground(new java.awt.Color(255, 255, 255));
        lblAss.setText("Assistant ");
        getContentPane().add(lblAss, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        lblCoach.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        lblCoach.setForeground(new java.awt.Color(255, 255, 255));
        lblCoach.setText("Default");
        getContentPane().add(lblCoach, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        lblName.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Default");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        lblC.setFont(new java.awt.Font("Book Antiqua", 1, 28)); // NOI18N
        lblC.setForeground(new java.awt.Color(255, 255, 255));
        lblC.setText("Coach");
        getContentPane().add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/view/image/secundary2.gif"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowPlayers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAss;
    private javax.swing.JLabel lblAssistant;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblCoach;
    private javax.swing.JLabel lblCon;
    private javax.swing.JLabel lblConfederacy;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tablePlayers;
    // End of variables declaration//GEN-END:variables

    @Override
    public void openWindow(Frame beforeWindow) {
        this.beforeWindow = beforeWindow;
        this.setVisible(true);

    }

    @Override
    public void jumpBeforeWindow() {
        this.dispose();
        beforeWindow.setVisible(true);
    }

    public JLabel getLblAssistant() {
        return lblAssistant;
    }

    public void setLblAssistant(JLabel lblAssistant) {
        this.lblAssistant = lblAssistant;
    }

    public JLabel getLblCoach() {
        return lblCoach;
    }

    public void setLblCoach(JLabel lblCoach) {
        this.lblCoach = lblCoach;
    }

    public JLabel getLblName() {
        return lblName;
    }

    public void setLblName(JLabel lblName) {
        this.lblName = lblName;
    }

    public JLabel getLblConfederacy() {
        return lblConfederacy;
    }

    public void setLblConfederacy(JLabel lblConfederacy) {
        this.lblConfederacy = lblConfederacy;
    }

    public Team getActualTeam() {
        return actualTeam;
    }

    public void setActualTeam(Team actualTeam) {
        this.actualTeam = actualTeam;
    }

    public JTable getTablePlayers() {
        return tablePlayers;
    }

    public void setTablePlayers(JTable tablePlayers) {
        this.tablePlayers = tablePlayers;
    }

    public JButton getBtnBack() {
        return btnBack;
    }

    public void setBtnBack(JButton btnBack) {
        this.btnBack = btnBack;
    }

    public JButton getBtnCreate() {
        return btnCreate;
    }

    public void setBtnCreate(JButton btnCreate) {
        this.btnCreate = btnCreate;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public void setBtnDelete(JButton btnDelete) {
        this.btnDelete = btnDelete;
    }

    public JButton getBtnUpdate() {
        return btnUpdate;
    }

    public void setBtnUpdate(JButton btnUpdate) {
        this.btnUpdate = btnUpdate;
    }

}
