/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.codeapp.view;

import java.awt.Frame;
import pk.codeapp.controller.ShowTablePositionsController;
import pk.codeapp.model.JumpWindow;

/**
 *
 * @author Daniel Amador
 */
public class ShowGroupPositions extends javax.swing.JFrame implements JumpWindow {

    private StatisticsScreen beforeWindow;
    ShowTablePositionsController controller;
    /**
     * Creates new form ShowGroupPositions
     */
    public ShowGroupPositions() {
        initComponents();
        controller= new ShowTablePositionsController(this);
        btnBack.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        GroupH = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        groupA = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        GroupB = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        GroupC = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        GroupD = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        GroupE = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        GroupF = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        GroupG = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        btnBack.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<2018 FIFA WORLD CUP RUSSIA™");
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(785, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 50));

        GroupH.setBackground(new java.awt.Color(0, 0, 0));
        GroupH.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        GroupH.setForeground(new java.awt.Color(255, 255, 255));
        GroupH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        GroupH.setOpaque(false);
        jScrollPane2.setViewportView(GroupH);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 550, 120));

        groupA.setBackground(new java.awt.Color(0, 0, 0));
        groupA.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        groupA.setForeground(new java.awt.Color(255, 255, 255));
        groupA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        groupA.setOpaque(false);
        jScrollPane3.setViewportView(groupA);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 550, 120));

        GroupB.setBackground(new java.awt.Color(0, 0, 0));
        GroupB.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        GroupB.setForeground(new java.awt.Color(255, 255, 255));
        GroupB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        GroupB.setOpaque(false);
        jScrollPane4.setViewportView(GroupB);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 550, 120));

        GroupC.setBackground(new java.awt.Color(0, 0, 0));
        GroupC.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        GroupC.setForeground(new java.awt.Color(255, 255, 255));
        GroupC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        GroupC.setOpaque(false);
        jScrollPane5.setViewportView(GroupC);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 550, 120));

        GroupD.setBackground(new java.awt.Color(0, 0, 0));
        GroupD.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        GroupD.setForeground(new java.awt.Color(255, 255, 255));
        GroupD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        GroupD.setOpaque(false);
        jScrollPane6.setViewportView(GroupD);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 550, 120));

        GroupE.setBackground(new java.awt.Color(0, 0, 0));
        GroupE.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        GroupE.setForeground(new java.awt.Color(255, 255, 255));
        GroupE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        GroupE.setOpaque(false);
        jScrollPane7.setViewportView(GroupE);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 550, 120));

        GroupF.setBackground(new java.awt.Color(0, 0, 0));
        GroupF.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        GroupF.setForeground(new java.awt.Color(255, 255, 255));
        GroupF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        GroupF.setOpaque(false);
        jScrollPane8.setViewportView(GroupF);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 550, 120));

        GroupG.setBackground(new java.awt.Color(0, 0, 0));
        GroupG.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        GroupG.setForeground(new java.awt.Color(255, 255, 255));
        GroupG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        GroupG.setOpaque(false);
        jScrollPane9.setViewportView(GroupG);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 550, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowGroupPositions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowGroupPositions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowGroupPositions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowGroupPositions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowGroupPositions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable GroupB;
    public javax.swing.JTable GroupC;
    public javax.swing.JTable GroupD;
    public javax.swing.JTable GroupE;
    public javax.swing.JTable GroupF;
    public javax.swing.JTable GroupG;
    public javax.swing.JTable GroupH;
    public javax.swing.JButton btnBack;
    public javax.swing.JTable groupA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
@Override
    public void openWindow(Frame beforeWindow) {
        this.beforeWindow = (StatisticsScreen) beforeWindow;
        this.setVisible(true);
    }

    @Override
    public void jumpBeforeWindow() {
        this.dispose();
        beforeWindow.setVisible(true);
    }
}
