/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.codeapp.view;

import java.awt.Frame;
import javax.swing.DefaultListModel;
import pk.codeapp.controller.AppController;
import pk.codeapp.model.JumpWindow;
import pk.codeapp.model.Team;

/**
 *
 * @author Jose Pablo Brenes
 */
public class TeamWithPlayers extends javax.swing.JFrame implements JumpWindow{

    /**
     * Creates new form teamWithPlayers
     */
    private Frame beforeWindow;
    private AppController controller = Lobby.controller;
    public TeamWithPlayers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblCoach = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblConfederency = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblAssistant = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTotalPlayer = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setBackground(new java.awt.Color(0, 0, 0));
        jList1.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 760, 510));

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Coach:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Show");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 590, 180, 50));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Players");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, -1, -1));

        lblCoach.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        lblCoach.setForeground(new java.awt.Color(255, 255, 255));
        lblCoach.setText("Default");
        getContentPane().add(lblCoach, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, 30));

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confederency:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        lblConfederency.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        lblConfederency.setForeground(new java.awt.Color(255, 255, 255));
        lblConfederency.setText("Default");
        getContentPane().add(lblConfederency, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, -1, 30));

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Assistant:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        lblAssistant.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        lblAssistant.setForeground(new java.awt.Color(255, 255, 255));
        lblAssistant.setText("Default");
        getContentPane().add(lblAssistant, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, 30));

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Players:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        lblTotalPlayer.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        lblTotalPlayer.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalPlayer.setText("Default");
        getContentPane().add(lblTotalPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, 30));

        lblName.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Default");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, 30));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Team:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Segundo Semestre 2017\\POO\\Proyecto#2\\RusiaIsComing\\WorldCup2018\\WorldCup2018\\WorldChampionCup\\src\\pk\\codeapp\\view\\image\\secundary5.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeamWithPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeamWithPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeamWithPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeamWithPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamWithPlayers().setVisible(true);
            }
        });
    }
    private void chargeTeam(){
        Team team =controller.getViewTeam();
        lblName.setText(team.getName());
        lblCoach.setText(team.getCoach());
        lblAssistant.setText(team.getAssistant());
        lblConfederency.setText(team.getConfederacy());
        lblTotalPlayer.setText(team.getCantPlayer()+"");
        
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAssistant;
    private javax.swing.JLabel lblCoach;
    private javax.swing.JLabel lblConfederency;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTotalPlayer;
    // End of variables declaration//GEN-END:variables

    @Override
    public void openWindow(Frame beforeWindow) {
       this.beforeWindow=beforeWindow;
       this.setVisible(true);
       chargeTeam();
    }

    @Override
    public void jumpBeforeWindow() {
      this.dispose();
      beforeWindow.setVisible(true);
      
    }
}
